name = "arknights-only-map"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "public"

# D1 数据库绑定（serverless SQLite）
[[d1_databases]]
binding = "DB"
database_name = "arknights-only-map"
database_id = "27a131d1-03b9-48b4-b169-89e0bad18f70"  # 执行 wrangler d1 create arknights-only-map 后回填
migrations_dir = "migrations"
